import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
import { BasketProvider } from "./components/Basket";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const DynamicNavigation = dynamic(() => import("./components/Navigation"), {
  ssr: false,
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Aureoma</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Asap:ital,wght@1,600&family=League+Spartan:wght@500&family=Pacifico&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className={inter.className}>
        <BasketProvider>
          <DynamicNavigation />
          {children}
        </BasketProvider>
      </body>
    </html>
  );
}
