export const SUPABASE_URL = "https://kozvstpfbkaselpgdsln.supabase.co";
export const SUPABASE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvenZzdHBmYmthc2VscGdkc2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTQ0OTQ2MTQsImV4cCI6MjAxMDA3MDYxNH0.dDaG8ZPrCoH6ghqUwbSwD_vTvMFGKDQCsadwyRY0vJk";
